[2024-03-15T21:17:28.372+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: simple_dag.simple_task scheduled__2024-03-14T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
